version: '3.7'

services:
  app:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - appdata:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links: 
      - phpfpm
  phpfpm:
    image: goralczykmarcin/php-fpm:8.1-magento
    volumes:
      - appdata:/var/www/html
    links: 
      - db
  db:
    image: mariadb:10.4
    command: --max_allowed_packet=64M
    volumes:
      - dbdata:/var/lib/mysql
    env_file: ./env/db.env

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 'vascoe'
    ports:
      - '3306:80'
  elasticsearch:
    image: elasticsearch:7.17.3
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      discovery.type: single-node
  rabbitmq:
    build: ./dockerfile/rabbitmq/3.9
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: ./env/rabbitmq.env
volumes:
  appdata:
    driver: local
    driver_opts:
      type: none
      device: ./src
      o: bind 
  dbdata:
  rabbitmqdata: