version: '3.7'

services:
  app:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - appdata:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links: 
      - phpfpm
  phpfpm:
    # build: ./dockerfile/phpfpm/8.1
    image: goralczykmarcin/php-fpm:8.1-magento
    volumes:
      - appdata:/var/www/html
    links: 
      - db

  # mysql:
  #   platform: linux/x86_64
  #   image: mysql:latest
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: magento
  #     MYSQL_USER: strony
  #     MYSQL_PASSWORD: vascoe
  #     MYSQL_ROOT_PASSWORD: vascoe
  db:
    image: mariadb:10.4
    command: --max_allowed_packet=64M
    # ports:
    #   - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment: 
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: vascoe
      MYSQL_DATABASE: magento
      MYSQL_USER: strony
      MYSQL_PASSWORD: vascoe
      # MYSQL_INTEGRATION_ROOT_PASSWORD: vascoe
      # MYSQL_INTEGRATION_DATABASE: magento_integration_tests
      # MYSQL_INTEGRATION_USER: strony
      # MYSQL_INTEGRATION_PASSWORD: vascoe
      # MYSQL_INTEGRATION_HOST: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 'vascoe'
    ports:
      - '3306:80'
  elasticsearch:
    image: elasticsearch:7.17.3
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      discovery.type: single-node
volumes:
  appdata:
    driver: local
    driver_opts:
      type: none
      device: ./src
      o: bind 
  dbdata: